# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: soaringsimulator
open_collective: # Replace with a single Open Collective username

custom: ['paypal.me/SoaringClouds', 'https://www.blockchain.com/btc/address/3QSTuvAqTsYEz39A8SUMQQiu2oNgBZLUbU', 'https://www.blockchain.com/eth/address/0x4110eceDEacf6304B53728ffF600CEE4B229cf3f']

